project:
  type: book
  output-dir: docs


book:
  title: "Modelado Bayesiano"
  subtitle: "Una introducción al modelado probabilista"
  author:
    - name: Osvaldo A. Martin 
      url: https://aloctavodia.github.io/
      affiliation: IMASL-CONICET
      affiliation-url: https://gmp.net.ar
      orcid: 0000-0001-7419-8978
      address: Italia 1556
      city: San Luis
      state: San Luis
      country: Argentina
      postal-code: 5700
  date: today
  #cover-image: cover.png

  chapters:
    - index.qmd
    - 00_Probabilidad.ipynb
    - 01_Inferencia_Bayesiana.ipynb
    - 02_Programación_probabilística.ipynb
    - 03_Modelos_jerárquicos.ipynb
    - 04_Diagnóstico_MCMC.ipynb
    - 05_Regresión_lineal.ipynb
    - 06_Generalizando_modelos_lineales.ipynb
    - 07_Comparación_de_modelos.ipynb

  page-navigation: true
  reader-mode: true
  page-footer: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Este obra está bajo <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">licencia Creative Commons Reconocimiento 4.0 Internacional</a>.
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        text: github
        menu:
          - text: Fuente
            url:  https://github.com/Grupo-de-modelado-probabilista/Modelado_Bayesiano
          - text: Reportar errores
            url:  https://github.com/Grupo-de-modelado-probabilista/Modelado_Bayesiano/issues/new
      - icon: cup
        href: https://cafecito.app/aloctavodia
        text: donaciones

format:
  html:
    toc: true
    code-line-numbers: true
    number-sections: true
    number-offset: -1
    lang: es
    language: 
      title-block-author-single: "Autor"
      title-block-published: "Última modificación"
      toggle-dark-mode: "Modo claro/oscuro"
      toggle-reader-mode: "Modo sin distracciones"
      search: "Buscar"
    

theme:
  light: cosmo
  dark: darkly

citation:
  type: book
  doi: https://doi.org/10.5281/zenodo.7851296
  issued: 2023/04/21
google-scholar: true