name: bayes
channels:
  - conda-forge
dependencies:
  - python<3.11
  - ipython>=8.6
  - jupyter>=1.0.0
  - ipympl>=0.9.2
  - pymc==5.3.0
  - seaborn>=0.12.1
  - arviz==0.15.1
  - pip>=22.3.1
  - pip:
    - preliz==0.3.0

